name="helloworld_dev"
version="1.0.0"
project="default"
plan="free"
dev=true

[code]
location="../code"
python_application="app:app"
health_check_endpoint="/health"
docker="ghcr.io/cosmian/mse-pytorch:20230104085621"