name = "data-anonymization-s3"
project = "default"
resource = "free"

[code]
location = "mse_src"
docker = "ghcr.io/cosmian/mse-anonymization:20230126164002"
python_application = "app:app"
healthcheck_endpoint = "/"
secrets="secrets.json"
