name = "digit-recognition"
project = "default"
hardware = "512m-eu-001"

[code]
location = "mse_src"
docker="ghcr.io/cosmian/mse-tensorflow:20230228091041"
python_application = "app:app"
healthcheck_endpoint = "/health"
