name="yaos_millionaires"
project="default"
hardware="4g-eu-001"

[code]
location="./mse_src"
python_application="app:app"
healthcheck_endpoint="/health"
docker="ghcr.io/cosmian/mse-flask:20230228091325"
