name="float_average-trusted"
project="default"
resource="free"

[code]
location="./mse_src"
python_application="app:app"
healthcheck_endpoint="/health"
docker="ghcr.io/cosmian/mse-flask:20230124182826"

[ssl]
domain_name="demo.owner.com"
private_key="key.pem"
certificate="cert.pem"
