name="float_average-trusted"
version="1.0.0"
project="default"
plan="free"

[code]
location="./mse_src"
python_application="app:app"
healthcheck_endpoint="/health"
docker="ghcr.io/cosmian/mse-flask:20230110142022"

[ssl]
domain_name="demo.owner.com"
private_key="key.pem"
certificate="cert.pem"
