FROM ghcr.io/cosmian/mse-base-beta:c706160c23a080e224bd9d5f26fdb3b529721c1b

RUN . /opt/venv/bin/activate && \
    pip3 install "flask==2.2.2" \
    "pandas==1.5.2" \
    "cosmian_lib_anonymization==0.1.2"