name = "data-anonymization-s3"
project = "default"
hardware = "4g-eu-001"

[code]
location = "mse_src"
docker = "ghcr.io/cosmian/mse-anonymization:20230228091120"
python_application = "app:app"
healthcheck_endpoint = "/health"
secrets="secrets.json"
