name = "data-anonymization-s3"
python_application = "app:app"
healthcheck_endpoint = "/health"
tests_cmd = "pytest"
tests_requirements = [
    "intel-sgx-ra",
    "pytest==7.2.0",
    "boto3==1.26",
]

[cloud]
project = "default"
hardware = "4g-eu-001"
code = "mse_src"
tests = "tests"
docker = "ghcr.io/cosmian/mse-anonymization:20230810125234"
secrets = "secrets.json"
