name = "sentiment_analysis"
project = "default"
resource = "free"

[code]
location = "mse_src"
docker="ghcr.io/cosmian/mse-nlp:20230228091156"
python_application = "app:app"
healthcheck_endpoint = "/health"
