name = "sentiment_analysis"
project = "default"
resource = "free"

[code]
location = "mse_src"
docker="ghcr.io/cosmian/mse-pytorch:20230228091413"
python_application = "app:app"
healthcheck_endpoint = "/health"
