name = "helloworld"
python_application = "app:app"
healthcheck_endpoint = "/health"
tests_cmd = "pytest"
tests_requirements = [
    "intel-sgx-ra",
    "pytest==7.2.0",
]

[cloud]
project = "default"
hardware = "4g-eu-001"
code = "mse_src"
tests = "tests"
docker = "ghcr.io/cosmian/mse-flask-beta:8bb7598ee7f975e9ab4d72b326361fd40ecc6a03"
