name="fastapi-helloworld"
project="default"
hardware="4g-eu-001"

[code]
location="mse_src"
python_application="app:app"
healthcheck_endpoint="/health"
docker="ghcr.io/cosmian/mse-fastapi:20230228091443"