name="merge_join"
version="1.0.0"
project="default"
plan="free"

[code]
location="./mse_src"
python_application="app:app"
healthcheck_endpoint="/health"
docker="ghcr.io/cosmian/mse-pytorch:20230119150226"