name = "yaos-millionaires-trusted"
python_application = "app:app"
healthcheck_endpoint = "/health"
tests_cmd = "pytest"
tests_requirements = [
    "intel-sgx-ra",
    "pytest==7.2.0",
]

[cloud]
project = "default"
hardware = "4g-eu-001"
code = "mse_src"
tests = "tests"
docker = "ghcr.io/cosmian/mse-flask:20230720104849"

[cloud.ssl]
domain_name = "demo.owner.com"
private_key = "key.pem"
certificate = "cert.pem"